tiagosiebler/bitget-api

README.md, examples/rest-trade-futures.ts, examples/rest-trade-spot.ts, package.json, src/util/BaseRestClient.ts
=> chore(): cleaning & readme

package.json, src/websocket-client.ts
- fix(#10) ping syntax for websockets
=> v1.1.1: fix(#10) ping syntax for websockets

src/futures-client.ts, src/types/request/futures.ts
Add missing a API endpoint
Modify order API
=> ADD: missing API (Modify Order)

package.json
=> v1.1.4, feat(#21) add modify futures order

package.json, src/types/request/v2/spot.ts
Update spot Kline intervals for V2
=> update SpotKlineInterval for V2

src/rest-client-v2.ts
i was looking for https://www.bitget.com/api-doc/spot/account/Get-SubAccount-TransferRecords 
but i didn't found if it already have i so sorry to bother
=> feat: add api main-sub-transfer-record

package.json
- feat(#26): add missing endpoint
=> v2.0.2: add missing spot transfer endpoint

src/rest-client-v2.ts
Adding Get Sub Account Deposit Records
https://www.bitget.com/api-doc/spot/account/Get-SubAccount-Deposit-Record
and Remove the extra comma ( my mistake )
=> feat: getSubAccountDepositRecords API

src/futures-client.ts
=> little fixes

package.json
=> v2.0.4: v1 fixes and missing endpoints

package-lock.json, package.json
=> v2.0.8: fix() fussy test, chore() bump dependencies

test/spot/private.write.test.ts
=> chore(): skip fussy test

package.json, src/rest-client-v2.ts, src/util/BaseRestClient.ts, src/util/requestUtils.ts
https://www.bitget.com/api-doc/common/demotrading/restapi
=> feat(v2.3.1): add demoTrading flag to REST Client for demo mode support

package-lock.json, test/spot/private.write.test.ts
=> chore(): simple test fix

package-lock.json, package.json, src/broker-client.ts
=> feat(v2.3.2): add v1 query broker detail endpoint

package-lock.json, package.json, src/util/BaseWSClient.ts, src/util/websocket-util.ts, src/websocket-client.ts
=> fix(v2.3.3): fallback to ws.close in browsers

package-lock.json, package.json, src/broker-client.ts
fix(v2.3.4): fixed typo for request types for getAgentCommissionDetail()
=> fix(v2.3.4): fixed typo for request types for getAgentCommissionDetail()

README.md, examples/rest-private-futures.ts, examples/rest-private-spot.ts, examples/rest-public-futures.ts, examples/rest-trade-futures.ts, examples/rest-trade-spot.ts, examples/ws-private.ts, examples/ws-public.ts
feat(): updated all examples to use v2 clients
=> feat(): updated all examples to use v2 clients

docs/endpointFunctionList.md, examples/apidoc/RestClientV2/earnRedeemSavings.js, examples/apidoc/RestClientV2/getFuturesDiscountRate.js, examples/apidoc/RestClientV2/getFuturesInterestExchangeRate.js, examples/apidoc/RestClientV2/getFuturesInterestHistory.js, examples/apidoc/RestClientV2/getFuturesInterestRateHistory.js, examples/apidoc/RestClientV2/getFuturesTriggerSubOrder.js, examples/apidoc/RestClientV2/setFuturesAssetMode.js, examples/apidoc/RestClientV2/spotBatchCancelandSubmitOrder.js, examples/apidoc/RestClientV2/spotCancelandSubmitOrder.js, package-lock.json, package.json, src/broker-client.ts
feat(v2.3.5): added missing affiliate endpoints to broker client
=> feat(v2.3.5): added missing affiliate endpoints to broker client 

.github/workflows/e2etests.yml, package.json, test/ws.private.test.ts, test/ws.public.test.ts
feat(): separated private and public tests
=> feat(): separated private and public tests

examples/rest-private-futures.ts, examples/rest-private-spot.ts, examples/rest-trade-futures.ts, examples/rest-trade-spot.ts, examples/ws-private.ts
=> chore(): updated examples 

docs/endpointFunctionList.md
chore(): update endpoint map logo
=> chore(): update endpoint map logo

src/util/BaseRestClient.ts, src/util/requestUtils.ts
As part of the PR, make sure you have:
=> feat(): added http keepAlive setting

package-lock.json, package.json, src/types/websockets/ws-general.ts, src/util/BaseWSClient.ts, src/util/websocket-util.ts
As part of the PR, make sure you have:
=> feat(v3.0.4): implement mechanism to disable heartbeat

package-lock.json, package.json, src/rest-client-v2.ts
As part of the PR, make sure you have:
=> fix(v3.0.6): GET request method for sub deposit/withdrawal records

docs/endpointFunctionList.md, examples/apidoc/RestClientV2/getAllSubDepositWithdrawalRecords.js, examples/apidoc/RestClientV2/getBrokerCommissions.js, examples/apidoc/RestClientV2/getBrokerSubaccounts.js, examples/apidoc/RestClientV2/getBrokerTradeVolume.js, examples/apidoc/RestClientV2/getSwitchUnionUsdt.js, examples/apidoc/RestClientV2/getUnionConfig.js, examples/apidoc/RestClientV2/getUnionTransferLimits.js, examples/apidoc/RestClientV2/subaccountWithdrawalRecords.js, examples/apidoc/RestClientV2/unionConvert.js, llms.txt, package-lock.json, package.json, src/rest-client-v2.ts, src/types/request/v2/broker.ts, src/types/request/v2/futures.ts, src/types/response/v2/broker.ts, src/types/response/v2/futures.ts
As part of the PR, make sure you have:
=> feat(v3.0.7): add missing endpoints
